config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get 'welcome/index'
    get 'welcome/faq'

    resources :users do
	  get :new_temp, on: :new
	  resources :pages, except: [:destroy] do
	  end
    end

    resources :user_sessions, only: [:create, :destroy]
    delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
    get '/sign_in', to: 'user_sessions#new', as: :sign_in

    resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/page.rb
class Page < ActiveRecord::Base
    belongs_to :user
    validates :date, uniqueness: {scope: :user}

    after_initialize do |page|
	page.date=Date.today if page.date==nil
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic
    validates :name, length: {maximum: 50}
    has_many :pages

    def deliver_password_reset_instructions!
	reset_perishable_token!
	PasswordResetMailer.reset_email(self).deliver_now
    end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    private

    def current_user_session
	return @current_user_session if defined?(@current_user_session)
	@current_user_session = UserSession.find
    end

    def current_user
	return @current_user if defined?(@current_user)
	@current_user = current_user_session && current_user_session.user
    end

    def current_user_guest?
	current_user && current_user.email.include?("morningpages.ink")
    end

    def alert_if_guest
	if current_user_guest?
	    flash[:info]="Enjoying this website? Consider #{(view_context.link_to "signing up", new_user_path, class: "alert-link").html_safe } (your pages will be kept)".html_safe
	end
    end

    helper_method :current_user_session, :current_user, :current_user_guest?, :alert_is_guest
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :alert_if_guest, only: [:new, :edit]

    def index
	@pages=current_user.pages.order(:date)
	if today_page_exists?
	    redirect_to edit_user_page_path(current_user,@pages.last)
	else
	    redirect_to new_user_page_path
	end
    end

    def new
	redirect_to edit_user_page_path(current_user, current_user.pages.last) if today_page_exists?
	@page = Page.new
    end

    def edit
	@page = current_user.pages.find(params[:id])
	render 'new'
    end

    def create
	@user = User.find(current_user.id)
	if (@page = @user.pages.create(page_params)).id!=nil
	    render json: @page
	else
	    render plain: "creation failed", status: 500
	end
    end

    def update
	@page = Page.find(params[:id])
	if @page.update(page_params)
	    render json: @page
	else
	    render plain: "update failed", status: 500
	end
    end

    def today_page_exists?
	current_user.pages.exists?(date: Date.today)
    end

    private

    def page_params
	params.require(:page).permit(:body)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
	@user=User.new
    end

    def edit
	@user = User.find_by(perishable_token: params[:id])
	redirect_to root_path unless @user
    end

    def create
	@user = User.find_by_email(params[:user][:email])
	if @user
	    @user.deliver_password_reset_instructions!
	    flash[:success] = "Instructions to reset your password have been emailed to you."
	    redirect_to root_path
	else
	    flash[:warning] = "No user was found with that email address"
	    @user=User.new
	    render :new
	end
    end

    def update
	@user = User.find_by(perishable_token: params[:id])
	if @user.update_attributes(password_reset_params)
	    flash[:success] = "Password successfully updated!"
	    redirect_to root_path
	else
	    render :edit
	end
    end

    private

    def password_reset_params
	params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    def new
	@user_session = UserSession.new
    end

    def create
	@user_session = UserSession.new(user_session_params)
	if @user_session.save
	    flash[:success] = "Welcome!"
	    redirect_to root_path
	else
	    render :new
	end
    end

    def destroy
	current_user_session.destroy
	@current_user=nil
	flash[:success] = "Goodbye!"
	redirect_to root_path
    end

    private

    def user_session_params
	params.require(:user_session).permit(:email, :password, :remember_me)
    end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController

    #register page
    def new
	if current_user_guest?
	    @user=current_user
	    @user.email=nil
	    @user.name=nil
	else
	    @user = User.new
	end
    end

    def edit
	@user = User.find(params[:id])
    end

    def create
	@user = User.new(users_params)
	if @user.save
	    flash[:success] = "Account registered!"
	    redirect_to root_path
	else
	    render :new
	end
    end

    def update
	@user = User.find(params[:id])
	if current_user_guest?
	    #register guest
	    if @user.update(users_params)
		flash[:success] = "Account registered!"
		redirect_to root_path
	    else render :new
	    end

	else
	    #regular update
	    @user.update(user_params)
	    render :edit
	end
    end

    #guest create
    def new_temp
	temp_password=SecureRandom.hex
	@user = User.new(name: "guest",
			 email: "guest-#{Time.now.to_i}@morningpages.ink",
	password: temp_password,
	    password_confirmation: temp_password)

	if @user.save
	    flash[:success] = "Welcome!"
	    return redirect_to user_pages_path(@user)
	end

	redirect_to root_path #something went wrong
    end

    private

    def users_params
	params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :alert_if_guest

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
	<title>MorningPages.ink - Where you write for self recovery.</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
    </head>
    <body>
	<div class="wrapper">
	    <nav id="custom-bootstrap-menu" class="navbar navbar-default">
		<div class="navbar-header">
		    <%= link_to raw('<span class="morning">MorningPages</span><span class="ink">.ink</span>'), root_path, class: 'logo navbar-brand' %>
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		    </button>
		</div>
		<div id="navbar" class="collapse navbar-collapse navbar-menubuilder">
		    <ul class="nav navbar-nav navbar-left">
			<% if current_user %>
			    <li><%= link_to 'Write my pages !', user_pages_path(current_user) %></li>
			<% end %>

			<li><%= link_to 'Faq', welcome_faq_path %></li>
		    </ul>
		    <ul class="nav navbar-nav pull-right">
			<% if current_user %>
			    <li><p>Hi <%= current_user.name %> !</p></li>
			    <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
			<% else %>
			    <li><%= link_to 'Sign In', sign_in_path %></li>
			<% end %>
		    </ul>
		</div>
	    </nav>

	    <div class="container">
		<% flash.each do |key, value| %>
		    <div class="alert alert-<%= key %>">
			<%= value %>
		    </div>
		<% end %>
		<% flash.clear %>
		<%= yield %>
	    </div>
	    <div id="push"></div>
	</div>
	<footer id="footer" class="footer hand text-center">
	</footer>

    </body>


</html>

app/views/pages/_list.html.erb
<div class="col-xs-12 col-sm-10 col-sm-offset-1 table-responsive borderless">
    <div class="row">
	<table class="table">
	    <tbody>
		<tr >
		    <% current_user.pages.order(:date).last(8).each do |p| %>
			<td class="text-center" > <%= link_to image_tag("note.png"), edit_user_page_path(current_user,p),class: "note-img" %>
			<br/>
			<%= p.date.strftime('%d/%m/%y') %> </td>
		    <% end %>
		    <% if !@_controller.today_page_exists? %>
			<td class="text-center" > <%= link_to image_tag("note.png"), new_user_page_path(current_user),class: "note-img" %>
			<br/>
			<%= Date.today.strftime('%d/%m/%y') %> </td>
		    <% end %>
		</tr>
	    </tbody>
	</table>
    </div>
</div>

app/views/pages/new.html.erb
<%= javascript_include_tag "pages" %>
<div class="row hand">
    <%= render 'list' %>
</div>
<div class="row hand">
    <div class="col-md-10 col-md-offset-1">
	<%= form_for [current_user,@page], :html => {:id => 'current_page'} do |f| %>
	    <h2><%= @page.date.to_formatted_s(:long_ordinal) %></h2>
	    <% if @current_user.pages.count <= 2 %>
		<div class="alert alert-warning alert-dismissible">
		    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    Feeling stuck ? Have a look at <%= link_to 'the beginners tips', welcome_faq_path(anchor: "tips"), class: "alert-link" %> !
		</div>
	    <% end %>
	    <%= f.text_area :body, class: 'form-control', rows: '8', autocomplete: "off", autocorrect: "off", autocapitalize: "off", spellcheck: "false" %>
	<% end %>
	<p class="pull-right status">
	<span id="saving">Your text is autosaved. Write something!</span><br/>
	<span id="todo"></span>
	</p>
    </div>
</div>

app/views/password_resets/edit.html.erb
<p> Change password </p>
<%= form_for @user,url: password_reset_path,method: :patch do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit 'Submit', class: 'btn btn-lg' %>
<% end %>

app/views/password_resets/new.html.erb
<p>
Password reset:
</p>
<%= form_for @user,url:password_resets_path do |f| %>
    <%= render 'shared/errors',object: @user %>
    <div class="form-group">
	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>
    </div>
    <%= f.submit "Send email", class:'btn' %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-warning errors">
	<div class="panel-heading">
	    <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
	</div>

	<ul class="panel-body list-group">
	    <% object.errors.full_messages.each do |msg| %>
		<li class="list-group-item"><%= msg %></li>
	    <% end %>
	</ul>
    </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
    <%= render 'shared/errors', object: @user_session %>

    <div class="form-group">
	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :remember_me %>
	<%= f.check_box :remember_me %>
    </div>

    <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %>
    <br/><br/>
    <%= link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default' %>

<% end %>

app/views/users/edit.html.erb
<div class="page-header">
    <h1>My profile</h1>
</div>

<%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="form-group">
	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.submit 'Update',class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="form-group">
	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/welcome/faq.html.erb
<div class="jumbotron written-content">
    <h1> FAQ </h1>
    <div class="container text-justify">
	<div class="row">
	    <h3>Who made this website ?</h3>
	    <p>
	    My name is Thomas, I'm a french software engineer. I discovered the morning pages taking Julia Cameron's course <i><a href="http://www.goodreads.com/book/show/615570.The_Artist_s_Way">The artist's way</a></i> about creativity recovery.
	    I found it a lot of <a href="#benefits">benefits</a>. So I decided to give others a chance to discover it.
	    </p>

	    <h3>Is it free ?</h3>
	    <p>
	    It is ! I give it to you guys and that's my pleasure.
	    </p>

	    <h3>Why would I prefer writing online rather than longhand writing?</h3>
	    <p>
	    Privacy. Your paper notebook is not password-protected and these pages are very private. Do not let someone find it in your bedroom.
	    </p>

	    <h3>Who can read my writings?</h3>
	    <p>
	    You and just you.
	    Your texts are encrypted before getting written to the database. In a near future you will be able to chose your own encryption key so even I won't be able to read your writings.
	    </p>

	    <h3>I don't have time !</h3>
	    <p>
	    You decide where your time goes. Here, time you invest is time for fun and self care. Can you imagine how much time you save doing things with a calm and clear mind, improved attention and memory? And how enjoyable it is?
	    </p>

	    <h3 id="benefits">What are the benefits?</h3>
	    <p>
	    They are legion. As a short term benefit, morning pages is unarguably a stress crusher. As long as it becomes a habit, you'll recover a sense of safety, identity, strength, compassion and much more. Whole books got written on the subject.
	    <span class="quote">“It is impossible to write morning pages for any extended period of time without coming into contract with an unexpected inner power”</span> Cameron wrote.
	    And who knows, maybe you will find and choose there your meaning of life ? (check out this short and excellent <a href="http://highexistence.com/hunter-s-thompsons-monumental-letter-on-how-to-find-meaning-and-purpose-in-life/">article</a>)
	    <span class="quote">“A man who procrastinates in CHOOSING his life will inevitably have his choice made for him by circumstance”</span>
	    </p>

	    <h3>Are there rules ? When/How many words/How much time should I write ?</h3>
	    <p>
	    It's up to you !
	    Once you get the trick, write as you feel you need it. that's it !
	    The correctness/spelling and quality of what you write do not matter. Just express yourself.
	    </p>

	    <h3 id="tips">I'm stuck :(</h3>
	    <p>
	    How do you feel ? (today/this week/in general) Write about that and ask ou why. <span class="quote">“I'm feeling happy/calm/nervous/sleepy/empty today. I don't know why... was it like this 10 years ago.... ? So many things happened... I feel...”</span> Get lost into your thoughts.
	    ...or just write a remake of <i>The Jungle Book</i> if you feel inspired :)
	    </p>
	</div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <div class="container">
	<div class="row">
	    <h3>Meet yourself</h3>

	    <p>What are the morning pages? Put simply, pages of free writing, strictly stream-of-consciousness : <span class="quote">&ldquo;Oh, god, another morning. I have NOTHING to say. I need&#8230; blah blah&rdquo;.</span> They might also, more ingloriously, be called <span class="i">brain drain.</span>
	    <br/>
	    <span class="i">There is no wrong way to do morning pages. </span>Write down <span class="i">whatever</span> comes to mind. Nothing is too petty, too silly, too stupid, or too weird to be included.</p>

	    <h3>Your writings are private</h3>

	    <p>The morning pages are not supposed to sound smart &ndash; although sometimes they might. Most times they won&rsquo;t, and nobody will ever know except you. Nobody is allowed to read your pages except you.</p>

	    <h3>Benefits are legion</h3>

	    <p>Free writing is an easy and active form of meditation. In minutes it makes you feel great and once a habit boosts your creativity, bettering mental health and capacities. The morning pages are often negative, self-pitying, repetitive, stilted or babyish, angry or bland &ndash; even silly sounding. <b>Good !</b> All that angry, whiny, petty stuff that you write down in the morning stands between you and you.  Worrying about the job, the laundry, the funny knock in the car, the weird look in your lover&rsquo;s eye &ndash; this stuff eddies through our subconscious and muddies our days. Get it on the page.</p>

	    <p class="i pull-right">Inspired from <a href="http://www.goodreads.com/book/show/615570.The_Artist_s_Way">The artist&rsquo;s way</a> (Julia Cameron), a world-class creativity recovery course.</p>
	</div>
	<div class="row text-center">
	    <div>
		<%= 
		    if !current_user
			"#{link_to 'Sign Up', new_user_path, class: 'btn btn-primary btn-lg'}
			or #{link_to 'Just try it!', new_temp_new_user_path, class: 'btn btn-success btn-lg'}".html_safe
		    else
			link_to 'Write now !', user_pages_path(current_user), class: 'btn btn-primary btn-lg'
			end
 %>

	</div>
	</div>
    </div>